#! /bin/bash
[ $1 -a -f $1 ]  || (echo "filename \"$1\" not found" && exit)

source ./env

diff <(./cool_main.byte $1 | grep -v  '\#.*')  <(reflexer examples/simple.cool | refparser  | refsemant | grep -v  '\#.*')

